apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnd-project

resources:
  - brevo-smtp-secret.yaml
  - cnd-france-scw-secret.yaml
  - cnpg-cluster.yaml
  - cnpg-scheduled-backup.yaml
  - cnpg-secret.yaml
  - helmrelease-valkey.yaml
  - helmrelease.yaml
  - jwt-secret.yaml
  - valkey-secret.yaml
