apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnd-matrix

resources:
  - cnd-france-scw-secret.yaml
  - cnpg-cluster-synapse.yaml
  - cnpg-cluster-mas.yaml
  - cnpg-scheduled-backup-synapse.yaml
  - cnpg-scheduled-backup-mas.yaml
  - synapse-cnpg-secret.yaml
  - mas-cnpg-secret.yaml
  - helmrelease.yaml
